<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypelocation="http://download.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>robot_interfaces</name>
  <version>0.0.0</version>
  <description>Robot interfaces message definitions</description>
  <maintainer email="wlzc@example.com">wlzc</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <!--构建时依赖-->
  <build_depend>rosidl_default_generators</build_depend>

  <depend>std_msgs</depend>
  <depend>action_msgs</depend>
  <depend>geometry_msgs</depend>
    <!-- 底盘反馈年龄使用Duration，显式声明已有CMake中使用的依赖。 -->
    <depend>builtin_interfaces</depend>
  <depend>nlohmann_json</depend>
  
  <!--运行时依赖-->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!--接口包分组标识-->

  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
